### ISSUE TITLE
对不起, 无法连接数据库, 请先检查数据库配置再继续进行安装

### ISSUE THREAD

**Issue by MichaelPan1026** [typecho/typecho#1101]
### 1. 该问题的重现步骤是什么？
无法安装
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx/1.21.0
- 数据库版本：mysql  Ver 8.0.25
- PHP 版本：PHP 7.2.3
- Typecho 版本：最新开发版（0e49d186f590c5e6791b6de401dfaea56a30e796）
- 浏览器版本：Firefox 89

nginx, mysql, php 都是用 docker 安装的。配置检查多变了并没有问题
![圖片](https://user-images.githubusercontent.com/26241105/120472986-21f5ab80-c3d9-11eb-98e9-f1448d7b5813.png)
![圖片](https://user-images.githubusercontent.com/26241105/120473133-481b4b80-c3d9-11eb-97e2-d4c069d18299.png)
![圖片](https://user-images.githubusercontent.com/26241105/120473167-50738680-c3d9-11eb-8b1a-3692d380bd8e.png)

**Comment by joyqi** [comment]
把docker-compose文件完整的贴上来

**Comment by MichaelPan1026** [comment]
> 
> 
> 把docker-compose文件完整的贴上来

```
version: "2.0"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./typecho:/var/www
      - ./nginx/cert:/etc/nginx/cert
      - /var/log/nginx:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - php
    networks:
      - web

  php:
    image: tsund/php:7.2.3-fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./typecho:/var/www
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql
    networks:
      - web

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    env_file:
      - mysql.env
    networks:
      - web

networks:
  web:
```
