### ISSUE TITLE
设置主题外观提交后，设置过的内容被清空了

### ISSUE THREAD

**Issue by lilming123** [typecho/typecho#1308]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
并没有复现这个问题，你得把你的版本信息说一下

**Comment by Raymondo-C** [comment]
同样出现这个问题

我的环境：
### 1. 该问题的重现步骤是什么？

安装完后，任意主题，包括默认主题，点击保存设置后，主题中所有的设置选项都为空。
再重新主题后可以恢复到默认设置。

### 2. 你期待的结果是什么？实际看到的又是什么？

期待的结果是：保存主题设置。
实际看到的是：主题设置被清空。

### 3. 问题出现的环境

- 操作系统版本：docke joyqi/typecho:nightly-php8.0-fpm-alpine
- Apache/NGINX 版本：docker nginx 1.21.1
- 数据库版本：mysql 5.7
- PHP 版本：php8.0
- Typecho 版本：1.2.0 正式版
- 浏览器版本：Chrome 101

docker compose:

```
version: "3.8"
services:
    nginx:
        build:
            context: "./nginx"
            dockerfile: "Dockerfile" # dockerfile 只是复制nginx配置文件
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./acme.sh:/etc/nginx/certs"
            - "./typecho:/app"
        environment:
            - TZ=Asia/Hong_Kong
            - ENV=production
        links:
            - typecho
    typecho:
        image: joyqi/typecho:nightly-php8.0-fpm-alpine
        volumes: 
            - ./typecho:/app
        restart: always
        environment: 
            - TIMEZONE=Asia/Hong_Kong
            - MEMORY_LIMIT=128M
            - MAX_POST_BODY=50M
            - TYPECHO_DB_ADAPTER=Pdo_Mysql
            - TYPECHO_DB_HOST=x.x.x.x
            - TYPECHO_DB_PORT=3306
            - TYPECHO_DB_USER=xxx
            - TYPECHO_DB_PASSWORD=123456
            - TYPECHO_DB_DATABASE=xxx
            - TYPECHO_SITE_URL=https://my_domain_name
```

nginx config:

```
server {
    listen              443 ssl http2;
    listen              [::]:443 ssl http2;
    server_name         icac.io www.icac.io;
    root                /app;

    # SSL
    ......

    # security
    include             nginxconfig.io/security.conf;

    # index.php
    index               index.php;

    # index.php fallback
    if (!-e $request_filename) {
            rewrite ^(.*)$ /index.php$1 last;
    }
 
    # handle .php
    location ~ .*\.php(\/.*)*$ {
        fastcgi_pass typecho:9000;
        set $path_info "";
        set $real_script_name $fastcgi_script_name;
        if ($fastcgi_script_name ~ "^(.+?\.php)(/.+)$") {
            set $real_script_name $1;
            set $path_info $2;
        }
        fastcgi_param SCRIPT_NAME $real_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$real_script_name;
        # 404
        try_files                     $fastcgi_script_name =404;

        # default fastcgi_params
        include                       fastcgi_params;

        # fastcgi settings
        fastcgi_index                 index.php;
        fastcgi_buffers               8 16k;
        fastcgi_buffer_size           32k;
    }

    # additional config
    include nginxconfig.io/general.conf;

    # assets, media
    location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
       expires    7d;
       access_log off;
    }

    # svg, fonts
    location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
       add_header Access-Control-Allow-Origin "*";
       expires    7d;
       access_log off;
    }

}

# HTTP redirect
......
```

过程中php未报错，但是发现修改主题设置时，POST内容中所有参数的值都为空。
![](https://s3.bmp.ovh/imgs/2022/05/29/57b72fe140431d60.png)
