### ISSUE TITLE
wiki 上的 GAE 搭建方法已经不能用了

### ISSUE THREAD

**Issue by yanyuechuixue** [typecho/typecho#778]
### 1. 该问题的重现步骤是什么？
使用 wiki 上的搭建方法
### 2. 你期待的结果是什么？实际看到的又是什么？
期待成功在 gae 上安装
### 3. 问题出现的环境
使用 gae 按照 wiki 上的方法安装
也尝试过其他的 app.yaml:
```
runtime: php55
env: standard
instance_class: F1
handlers:
  - url: "/favicon\\.ico"
    static_files: favicon.ico
    require_matching_file: false
    upload: "favicon\\.ico"
  - url: "/(.*\\.(css|js))$"
    static_files: "__static__/\\1"
    require_matching_file: false
    upload: "__static__/.*\\.(css|js)$"
  - url: "/usr/(.*\\.(ico|jpg|png|gif))$"
    static_files: "__static__/usr/\\1"
    require_matching_file: false
    upload: "__static__/usr/.*\\.(ico|jpg|png|gif)$"
  - url: "/(.*\\.(ico|jpg|png|gif))$"
    static_files: "\\1"
    require_matching_file: false
    upload: ".*\\.(ico|jpg|png|gif)$"
  - url: /admin/(.+)
    script: "admin/\\1"
  - url: /usr/(.+)
    script: "usr/\\1"
  - url: /var/(.+)
    script: "var/\\1"
  - url: /admin/
    script: admin/index.php
  - url: /install.php
    script: install.php
  - url: /(.+)?/?
    script: index.php
  - url: '.*'
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
```
 错误是重定向过多.
